USERNAME: 'andrii'
PASSWORD: 'andrii'
MAILUSER: 'thinkiny.ads@gmail.com'
MAILSPASS: 'GH2020ADS'
FACEBOOK_KEY: '634942260606979'
FACEBOOK_SECRET: '234b5aaaf28a2f1690bbac323648bef2'
GOOGLE_KEY: '731415562513-carb83vkcbf6vltaq8gkqm7aksae4jrl.apps.googleusercontent.com'
GOOGLE_SECRET: 'jraYq26uQ69isXvyqwwcvmCZ'