USERNAME: 'andrii'
PASSWORD: 'andrii'
MAILUSER: 'thinkiny.ads@gmail.com'
MAILSPASS: 'GH2020ADS'
FACEBOOK_KEY: '502395977082303'
FACEBOOK_SECRET: '92bfe99fd67dba9bed0eac07155e17ec'
GOOGLE_KEY: '731415562513-rik0c97e7qnl5a9kh96cjtjonisan58l.apps.googleusercontent.com'
GOOGLE_SECRET: 'DndaPe7sggiGwjCQEoKWwVx2'