USERNAME: 'andrii'
PASSWORD: 'andrii'
MAILUSER: 'thinkiny.ads@gmail.com'
MAILSPASS: 'GH2020ADS'
FACEBOOK_KEY: '502395977082303'
FACEBOOK_SECRET: '92bfe99fd67dba9bed0eac07155e17ec'
GOOGLE_KEY: '731415562513-carb83vkcbf6vltaq8gkqm7aksae4jrl.apps.googleusercontent.com'
GOOGLE_SECRET: 'jraYq26uQ69isXvyqwwcvmCZ'