USERNAME: 'andrii'
PASSWORD: 'andrii'
MAILUSER: 'thinkiny.ads@gmail.com'
MAILSPASS: 'GH2020ADS'
FACEBOOK_KEY: '502395977082303'
FACEBOOK_SECRET: '92bfe99fd67dba9bed0eac07155e17ec'
GOOGLE_KEY: '731415562513-h5e1kn5db8s3nacu3710105giv8abql6.apps.googleusercontent.com'
GOOGLE_SECRET: '7meIrbWm-TvPRxA9M_Fzpsvi'